// Command apidocs writes docs/api.org from the route table of the server.
// The table registers the routes at runtime, so a route that serves is a
// route that this file documents.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"strings"

	"jump-pad/internal/api"
	"jump-pad/internal/config"
	"jump-pad/internal/httpserver"
)

// docsToken is a placeholder admin token. The generator needs one, so the
// admin routes appear in the table. No server runs here.
const docsToken = "documentation-placeholder-token"

func main() {
	out := flag.String("out", "docs/api.org", "file to write")
	flag.Parse()

	cfg := config.Defaults()
	cfg.AdminToken = docsToken
	routes := httpserver.New(nil, cfg).RouteTable()

	if err := os.WriteFile(*out, []byte(render(routes)), 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("wrote %s with %d routes\n", *out, len(routes))
}

// render writes the whole document, one section per access level.
func render(routes []api.Route) string {
	var page strings.Builder
	page.WriteString("#+TITLE: jump-pad API\n")
	page.WriteString("\n")
	page.WriteString("Generated from the route table by ~cmd/apidocs~. Do not edit this file\n")
	page.WriteString("by hand, because the next run overwrites it. Run ~just apidocs~ after a\n")
	page.WriteString("route changes.\n")

	for _, group := range []struct {
		access api.Access
		title  string
		lead   string
	}{
		{api.Public, "Open to everyone", "No token. A visitor reaches these routes."},
		{api.CreateToken, "Create token", "These routes need the create token when ~auth_token~ is set. The token arrives in the ~X-Auth-Token~ header, or in a ~token~ query parameter."},
		{api.AdminToken, "Admin token", "These routes exist only when ~admin_token~ is set, and they need that token in the ~X-Auth-Token~ header. A query parameter is not accepted, because a token in a URL reaches logs and history."},
	} {
		page.WriteString(fmt.Sprintf("\n* %s\n\n%s\n", group.title, group.lead))
		for _, route := range routes {
			if route.Access == group.access {
				page.WriteString(renderRoute(route))
			}
		}
	}

	return page.String()
}

// renderRoute writes one route and its parameter table.
func renderRoute(route api.Route) string {
	var block strings.Builder
	block.WriteString(fmt.Sprintf("\n** ~%s %s~\n\n%s\n", route.Method, route.Pattern, route.Summary))
	if len(route.Params) == 0 {
		return block.String()
	}

	block.WriteString("\n| Field | Required | Meaning |\n|-------+----------+---------|\n")
	for _, param := range route.Params {
		required := "no"
		if param.Required {
			required = "yes"
		}
		block.WriteString(fmt.Sprintf("| ~%s~ | %s | %s |\n", param.Name, required, param.Description))
	}
	return block.String()
}
